repos:
  # -------------------------
  # Ruff (lint + formatter)
  # -------------------------
  - repo: local
    hooks:
      - id: ruff
        name: ruff (lint)
        entry: poetry run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        types: [python]
        pass_filenames: true

  # -------------------------
  # MyPy
  # -------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pyyaml
          - types-requests
          - pydantic

  # -------------------------
  # CSpell (spell checking)
  # -------------------------
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v10.0.0
    hooks:
      - id: cspell
        args: ["--config", ".pre-commit-data/cspell.json", "--no-progress"]
        files: ^(src/|tests/|docs/)