task: classification

data:
  top_k_variants: null
  split_quantile: 0.8

prefix:
  min_length: 3
  # max_length: 10

features:
  enabled_features:
    - BasicControlFlowFeatures
  exclude_features: []

models:
  majority_class_baseline:
    model_type: DummyClassifier
    params:
      strategy: most_frequent
    param_grid: {}
