task: regression
checkpoint_dir: ../data/checkpoints

data:
  valid_end_activities:
    - "W_Validate application"
    - "W_Call after offers"
    - "W_Call incomplete files"
    - "O_Cancelled"
    - "A_Denied"
  top_k_variants: null
  split_quantile: 0.8

prefix:
  min_length: 3
  # max_length: 10

features:
  enabled_features:
    - BasicControlFlowFeatures
  exclude_features: []

models:
  mean_baseline:
    model_type: DummyRegressor
    params:
      strategy: mean
    param_grid: {}
